name: gtk-theme-arc
build-base: core24
base: bare
version: '20221218'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: Arc GTK theme
description: |
  A Snap that allows you to use Arc GTK themes in Snap apps
grade: stable
confinement: strict

slots:
  gtk-2-themes:
    interface: content
    source:
      read:
        - $SNAP/share/gtk2/Arc
        - $SNAP/share/gtk2/Arc-Dark
        - $SNAP/share/gtk2/Arc-Darker
        - $SNAP/share/gtk2/Arc-Lighter
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/Arc
        - $SNAP/share/themes/Arc-Dark
        - $SNAP/share/themes/Arc-Darker
        - $SNAP/share/themes/Arc-Lighter
parts:
  gtk-2-themes:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/universe/a/arc-theme/arc-theme_20221218-1ubuntu1_all.deb
    organize:
      usr/share/themes: share/gtk2
    prime:
      - share/gtk2/*/gtk-2.0
  gtk-3-themes:
    plugin: dump
    source: http://archive.ubuntu.com/ubuntu/pool/universe/a/arc-theme/arc-theme_20221218-1ubuntu1_all.deb
    organize:
      usr/share/themes: share/themes
    prime:
      - share/themes/*/gtk-3.0
      - share/themes/*/gtk-4.0
